config/routes.rb
Rails.application.routes.draw do
  resources :rsvps, only:[:create, :update, :destroy, :show]
  resources :events do
    resources :rsvps, only:[:create, :update, :destroy]
  end
  resources :users, only: [:new, :create, :edit, :update, :show] do
    resources :events, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  end
  root 'sessions#home'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#logoff'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# create_table "events", force: :cascade do |t|
#     t.string "title"
#     t.string "description"
#     t.datetime "date"
#     t.string "location"
#     t.integer "user_id"
#     t.datetime "created_at", null: false
#     t.datetime "updated_at", null: false
#   end

class Event < ApplicationRecord
    belongs_to :user
    has_many :rsvps, dependent: :destroy
    has_many :users, through: :rsvps
    scope :upcoming, -> {where("date > ?", Time.zone.now)}
    scope :sorted, -> {order(date: :asc)}
    # Ex:- scope :active, -> {where(:active => true)}

    def self.ten_closest
        Event.upcoming.order(date: :asc).limit(10)
    end
    


end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
    belongs_to :user
    belongs_to :event
    validates :event, :user, presence: true
    validates :user_id, uniqueness: {scope: :event_id}
end

app/models/user.rb
class User < ApplicationRecord
    #Validations
    validates :user_name, presence: true
    validates :user_name, uniqueness: { case_sensitive: false }
    has_secure_password
    #Associations
    has_many :events
    has_many :rsvps
    has_many :rsvped_events, through: :rsvps, source: :event
    
    def self.from_omniauth(auth)
        
        where(email: auth.info.email).first_or_initialize do |user|
         # binding.pry
          user.user_name = auth.info.name
          user.first_name = auth.info.first_name
          user.last_name = auth.info.last_name
         # binding.pry
          user.email = auth.info.email
          user.password = SecureRandom.hex
        end
     end

    def full_name
        "#{self.first_name} #{self.last_name}"
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login
    include ApplicationHelper
    

    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_permission, only: [:edit]
    def new
        @event = Event.new
    end

    def create
        #binding.pry
        @event = Event.new(event_params)
        if @event.save
            render json: @event, status: 201
        end

    end

    def index
        if params[:user_id]
            @user = User.find(params[:user_id])
            if params[:rsvpd]
                @events = User.find(params[:user_id]).rsvped_events
            else
                @events = User.find(params[:user_id]).events
            end
        else
            @events = Event.upcoming.sorted
        end
        respond_to do |format|
            format.html { render :index }
            format.json { render json: @events}
        end
       # binding.pry
    end

    def show
        @event = Event.find(params[:id])
        @rsvp = Rsvp.new
        respond_to do |format|
            format.html { render :show }
            format.json {render json: @event}
        end
    end

    def destroy
        Event.find(params[:id]).destroy
        redirect_to user_events_path(current_user.id)
    end

    def edit
        @event=Event.find(params[:id])
    end

    def update
        @event=Event.find(params[:id])
        @event.update(event_params)
        redirect_to event_path(@event)
    end

    private
    def event_params
        params.require(:event).permit(:title, :description, :location, :date, :user_id)
    end

    def require_permission
        if current_user != Event.find(params[:id]).user
          redirect_to event_path(params[:id]), :flash => {error: "Permission Denied"}
        end
    end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
    def create
        @rsvp = Rsvp.new(rsvp_params)
        @rsvp.save
        redirect_to event_path(params[:rsvp][:event_id])
    end

    def show
        @rsvp = Rsvp.find(params[:id])
        respond_to do |format|
            format.json { render json: @rsvp }
        end
    end

    def update
        @rsvp = Rsvp.find_by(user_id: params[:rsvp][:user_id], event_id: params[:rsvp][:event_id])
        @rsvp.update(rsvp_params)
    end

    def destroy
        @rsvp = Rsvp.find(params[:id])
        #binding.pry
        @rsvp.destroy
        redirect_to root_path
        
    end

    private
    def rsvp_params
        params.require(:rsvp).permit(:attending, :event_id, :user_id, :note)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_login, only: [:home, :new, :create, :omniauth]
    
    def home
        @events = Event.ten_closest
    end

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(user_name: params[:user][:user_name])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to root_path
        else
            flash[:error] = "Authentication Failed."
            redirect_to login_path
        end
    end

    def destroy
        session.delete :user_id
        redirect_to root_path
    end

    def logoff
        session.delete :user_id
        redirect_to root_path
    end

    def omniauth
        @user = User.from_omniauth(auth)
        #binding.pry
        @user.save
        session[:user_id] = @user.id
        redirect_to root_path
    end

    private
    def auth
        request.env['omniauth.auth']
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_permission, only: [:edit]
    skip_before_action :require_login, only: [:new, :create]
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            render 'new'
        end
    end
    def show
        @user = User.find(params[:id])
        respond_to do |format|
            format.html { render :show }
            format.json { render json: @user}
        end
    end

    def edit
        @user=User.find(params[:id])
    end

    def update
        @user=User.find(params[:id])
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    private

    def user_params
        params.require(:user).permit(:user_name, :password, :password_confirmation, :first_name, :last_name, :bio)
    end

    def require_permission
        if current_user != User.find(params[:id])
          redirect_to user_path(params[:id]), :flash => {error: "Permission Denied"}
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def require_login
        unless logged_in?
          flash[:error] = "You must be logged in to perform this action."
          redirect_to login_path
        end
    end
    

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end

    def my_resource?(resource)
        if !resource.is_a?(User)
            if resource.user_id == current_user.id
                return true
            else
                return false
            end
        else
            if resource.id == current_user.id
                return true
            else
                return false
            end
        end
    end
end

app/helpers/events_helper.rb
module EventsHelper
    def rsvpd?(event_id, user_id)
        rsvp = Rsvp.find_by(event_id: event_id, user_id: user_id)
        if rsvp && rsvp.attending
            return true
        else
            return false
        end
    end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_eventlist.html.erb
    <ul class = "list-group">
        <% events.each do |event| %>
            <li class ="list-group-item" ><%= link_to  event.title, event %> <br> 
            
                <div id="<%=event.id%>">
                    <div id="title-<%=event.id%>"></div>
                    <div id="organizer-<%=event.id%>"></div>
                    <div id="date-<%=event.id%>"></div>
                    <div id="location-<%=event.id%>"></div>
                    <div id="description-<%=event.id%>"></div>
                    <div id="url-<%=event.id%>"></div>
                </div>
                <button class="btn btn-primary js-more" data-id="<%=event.id%>">View Event</button>
            </li>
        <%end%>
    </ul>

app/views/events/_form.html.erb
<div id="newEvent">
<%= form_for( @event) do |f| %>

    <%if @event.errors.any?%>
        <h2>Errors:</h2>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <%end%>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="form-group">
    <%= f.label :title %>
    <%=f.text_field :title, required: true, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :description %>
    <%=f.text_area :description, required: true, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :location %>
    <%=f.text_field :location, required: true, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= f.label :date %>
    <%= f.datetime_field :date, required: true, class: "form-control" %>
    </div>
    
    <%=f.submit  class: "btn btn-success"%>
<% end %>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%=render 'form'%>

app/views/events/index.html.erb
<%if params[:user_id] && params[:rsvpd]%>
<h1>Events <%=@user.first_name%> is attending:</h1>
<%elsif params[:user_id]%>
    <h1><%=@user.first_name%>'s Events:</h1>
<%else%>
<h1>Events:</h1>
<%end%>




<%= render partial: "eventlist", locals: {events: @events}%>
<script type="text/javascript" charset="utf-8">
  jQuery(function () {

    class User{
    constructor (json){
        this.id = json["id"]
        this.first_name = json["first_name"]
        this.last_name = json["last_name"]
        this.bio = json["bio"]
        this.email = json["email"]
    }

    full_name(){
        return `${this.first_name} ${this.last_name}`
    }
}



    $(".js-more").on("click",function(e){
        e.stopPropagation()
        let id = $(this).attr("data-id");
        jQuery.getJSON("/events/" + id + ".json", function(data){
            let organizer = new User(data["user"])
            $(`#title-${id}`).text(`Title: ${data["title"]}`)
            $(`#organizer-${id}`).text(`Organizer: ${organizer.full_name()} `)
            $(`#date-${id}`).text(`Date: ${data["date"].split('T')[0]}`)
            $(`#location-${id}`).text(`Location: ${data["location"]}`)
            $(`#description-${id}`).text(`Description: ${data["description"]}`)
        })
        
    })
  });
</script>

app/views/events/new.html.erb
<h1>Create New Event</h1>
<%=render 'form'%>
<div id="createdEvent">


</div>


<script type="text/javascript" charset="utf-8">
  $(function () {
    $('form').submit(function(event) {
      event.preventDefault();
      var values = $(this).serialize();
      var posting = $.post('/events', values);
      posting.done(function(data){
          console.log(data)
          $("#newEvent").remove();
          $("h1").remove();
          $("#createdEvent").append(`<h1>${data["title"]}</h1>`)
          $("#createdEvent").append(`<h2>Event Organizer: ${data["user"]["first_name"]} ${data["user"]["last_name"]}</h1>`)
          $("#createdEvent").append(`<h2>Date: ${data["date"].split('T')[0]}</h2>`)
          $("#createdEvent").append(`<h2>Description:</h2> <p> ${data["description"]}</p>`)
          $("#createdEvent").append(`<a class="btn btn-dark" href="/events/${data["id"]}/edit">Edit Event</a>`)
      });
    });
  });
</script>


app/views/events/show.html.erb
<%if flash[:error]%>
    <div class="alert alert-danger" role="alert">
    <%= flash[:error]%>
    </div>
<%end%>
<h1><%= @event.title %></h1>
<h2>Event Organizer: <%= link_to  @event.user.full_name, @event.user %></h2>
<h2>Date: <%=@event.date.strftime("%b %e, %l:%M %p")%></h2>
<h2>Location: <%= @event.location %></h2>
<h2>Description</h2>
<p><%= @event.description %></p>
<h3><%=@event.users.count%> Users Attending<h3>
<div class="attending">
    <ul id="attending">

    </ul>
</div>
 <button class="btn btn-primary attendees" data-id="<%=@event.id%>" type="button">
    Show Attendees
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
  <ul>
    <%@event.users.each do |user|%>
        <%rsvp = user.rsvps.find_by(event_id: @event.id)%>
       <li> <%= link_to  "#{user.first_name} #{user.last_name}", user %> </li>
       <%="Note - #{rsvp.note}"  if rsvp.note%>
    <%end%>
    </ul>
  </div>
</div>
<%= render partial: "rsvps/rsvpbutton1" %>
<br>
<% if my_resource?(@event)%>
<div style ="display:flex;">
<%= link_to  "Edit Event", edit_event_path(@event), class: "btn btn-dark" %>  
<div class="divider"> </div>
<%= button_to "Delete Event", {:controller => :events,:action => 'destroy', :id => @event.id }, :method => :delete, class: "btn btn-danger" %>
</div>
<%end%>

<script type="text/javascript"  charset="utf-8">
  $(function () {
    $(".attendees").one("click", function(){
      let id = $(this).attr("data-id");
      $.get(`/events/${id}.json`, function(data){
        let rsvps = data["rsvps"]
        rsvps.forEach(rsvp => {
          console.log(rsvp)
          let userId = rsvp["user_id"]
          $.get(`/users/${userId}.json`, function(data){
            console.log(data["first_name"])
            $(`#attending`).append(`<li>${data["first_name"]} ${data["last_name"]} <br> Note: ${rsvp["note"]}</li>`)
            
          })
            
        });
      })
    })
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Social Events</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag "main.css" %>
  
  </head>
  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="/">
              <img src="https://i.imgur.com/5h1zCqP.png" alt="">
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <%if logged_in?%>
              <li class="nav-item">
                <a class="nav-link" href="/events">Events</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/users/<%=current_user.id%>">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
            <%else%>
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/signup">Sign up</a>
            </li>
            <%end%>
          </ul>
        </div>
      </div>
    </nav>


    <div class="wrapper">

        <%= yield %>

      <footer class="branding">
        <small>&copy; 2019 <strong>Social Events</strong></small>
      </footer>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <!--[if lt IE 7]>
      <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
      <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
  </body>
</html>

app/views/rsvps/_rsvpbutton.html.erb
<%if !rsvpd?(@event.id, current_user.id)%>
    <%= form_for( @rsvp = Rsvp.find_or_create_by(user_id: current_user.id, event_id: @event.id) ) do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.hidden_field :event_id, value: @event.id %>
        <%= f.hidden_field :attending, value: true %>
        <%=f.submit "RSVP"%>
    <% end %>
<%else%>
    <%@rsvp = Rsvp.find_by(user_id: current_user.id, event_id: @event.id)%>
    <%= button_to  "CANCEL", @rsvp, { method: "delete" } %>
<%end%>


app/views/rsvps/_rsvpbutton1.html.erb
<%if !rsvpd?(@event.id, current_user.id)%>
        <%= form_tag("/rsvps", method: :create) do %>
             <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
             <%= text_field_tag "rsvp[note]"%>
             <%= hidden_field_tag "rsvp[user_id]", @current_user.id %>
             <%= hidden_field_tag "rsvp[event_id]", @event.id %>
             <%= hidden_field_tag "rsvp[attending]", "true" %>
             <%= submit_tag "RSVP", class: "btn btn-success" %>
        <% end %>
<%else%>
        <%= form_tag("/rsvps/#{Rsvp.find_by(user_id: current_user.id, event_id: @event.id).id}", method: :delete) do %>
             <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
             <%= hidden_field_tag "rsvp[user_id]", @current_user.id %>
             <%= hidden_field_tag "rsvp[event_id]", @event.id %>
             <%= submit_tag "Cancel Rsvp", class: "btn btn-danger" %>
        <% end %>
<%end%>


app/views/users/edit.html.erb
<%= form_for( @user) do |f| %>

    <%if @user.errors.any?%>
        <h2>Errors:</h2>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <%end%>

    <div class="form-group">
    <%= f.label :bio %>
    <%=f.text_area :bio, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :password %>
    <%=f.password_field :password, required: true, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :password_confirmation %>
    <%=f.password_field :password_confirmation, required: true, class: "form-control"%>
    </div>
    <%=f.submit class: "btn btn-success"%>
<% end %>

app/views/users/new.html.erb
<%= form_for( @user) do |f| %>

    <%if @user.errors.any?%>
        <h2>Errors:</h2>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    <%end%>
    <div class="form-group">
    <%= f.label :user_name %>
    <%=f.text_field :user_name, required: true, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :first_name %>
    <%=f.text_field :first_name,  class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :last_name %>
    <%=f.text_field :last_name, required: true, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :password %>
    <%=f.password_field :password, required: true, class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :password_confirmation %>
    <%=f.password_field :password_confirmation, required: true, class: "form-control"%>
    </div>
    <%=f.submit "Sign up!", class: "btn btn-success"%>
<% end %>

app/views/users/show.html.erb
<%if flash[:error]%>
    <div class="alert alert-danger" role="alert">
    <%= flash[:error]%>
    </div>
<%end%>
<%if my_resource?(@user)%>
    <h1>Your Profile:</h1>
<%else%>
    <h1><%=@user.first_name%>'s Profile:</h1>
<%end%>
<div>
<h2>Name: <%=@user.first_name%> <%=@user.last_name%></h2>
<h2>About <%=@user.first_name%>:</h2> <p><%=@user.bio%></p>
</div>
<div>
<h2>Attending Upcoming Events:</h2>
        <ul class = "list-group">
        <% @user.rsvped_events.upcoming.each do |event| %>
            <li class ="list-group-item"><%= link_to  event.title, event %>, <big>Location:</big> <%=event.location%>, <big>Date:</big> <%=event.date.strftime("%A, %d %b %Y %l:%M %p")%></li>
            </li>
        <%end%>
    </ul>
</div>

<%if my_resource?(@user)%>
    <br>
    <%= link_to  "Edit Profile", edit_user_path(@user), class: "btn btn-dark" %>
    
<%end%>

app/views/users/welcome.html.erb
<h1>Hello</h1>
<%if session[:user_id]%>
    <%=User.find(session[:user_id]).user_name%>
    <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
    <input type=submit value='logout' class => "btn btn-danger" >
    <% end %>
    <%= link_to  "Create New Event", new_user_event_url(current_user.id) %>
<%end%>